/**
 * Email Sending Utility for Teaching Commands
 *
 * Shared utility for resolving email recipients, formatting content
 * as email, and building send instructions for the himalaya MCP tool.
 * Used by: solution, assignment, exam, quiz, rubric commands.
 */

/**
 * Resolve email recipient from options and config.
 *
 * Resolution order:
 *   1. Explicit email from --send flag value (if non-empty string, not 'true')
 *   2. course.staff.ta_email from teach-config.yml
 *   3. course_info.instructor_email from teach-config.yml
 *
 * @param {object} options - Command options with .send value
 * @param {object} config - Parsed teach-config.yml config object
 * @returns {string|null} Email address or null if none found
 */
export function resolveRecipient(options, config) {
  // Explicit email passed via --send email@example.com
  if (typeof options.send === 'string' && options.send !== 'true' && options.send.length > 0) {
    return options.send;
  }

  // Look up from config hierarchy
  const scholar = config?.scholar || config || {};
  const taEmail = scholar?.course?.staff?.ta_email;
  if (taEmail) return taEmail;

  const instructorEmail = scholar?.course_info?.instructor_email;
  if (instructorEmail) return instructorEmail;

  return null;
}

/**
 * Content type display names for email subjects.
 * @type {Record<string, string>}
 */
const CONTENT_TYPE_LABELS = {
  solution: 'Solution Key',
  assignment: 'Assignment',
  exam: 'Exam',
  quiz: 'Quiz',
  rubric: 'Grading Rubric'
};

/**
 * Format generated content as an email.
 *
 * @param {string} contentType - One of: 'solution', 'assignment', 'exam', 'quiz', 'rubric'
 * @param {object} content - Generated content object (varies by type)
 * @param {object} options - Command options
 * @param {string} [options.courseCode] - Course code (e.g., 'STAT-440')
 * @param {string} [options.topic] - Topic or title
 * @param {string} [options.outputPath] - Path to the saved file
 * @returns {{ subject: string, body: string }}
 */
export function formatEmail(contentType, content, options = {}) {
  const label = CONTENT_TYPE_LABELS[contentType] || contentType;
  const courseCode = options.courseCode || '';
  const topic = options.topic || content?.title || content?.assignment_title || '';

  // Build subject line
  const subjectParts = [];
  if (courseCode) subjectParts.push(`[${courseCode}]`);
  subjectParts.push(`${label}:`);
  subjectParts.push(topic || 'Generated Content');
  const subject = subjectParts.join(' ');

  // Build body
  const bodyLines = [];
  bodyLines.push(`${label} Generated by Scholar`);
  bodyLines.push('='.repeat(40));
  bodyLines.push('');

  if (courseCode) {
    bodyLines.push(`Course: ${courseCode}`);
  }
  if (topic) {
    bodyLines.push(`Topic: ${topic}`);
  }
  bodyLines.push(`Type: ${label}`);
  bodyLines.push(`Generated: ${new Date().toISOString().split('T')[0]}`);
  bodyLines.push('');

  // Include content summary based on type
  if (contentType === 'solution' && content?.solutions) {
    const problemCount = Object.keys(content.solutions).length;
    bodyLines.push(`Solutions for ${problemCount} problem(s) included.`);
  } else if (contentType === 'assignment' && content?.problems) {
    bodyLines.push(`Assignment with ${content.problems.length} problem(s).`);
    if (content.total_points) {
      bodyLines.push(`Total points: ${content.total_points}`);
    }
  } else if (contentType === 'exam' && content?.questions) {
    bodyLines.push(`Exam with ${content.questions.length} question(s).`);
    if (content.duration_minutes) {
      bodyLines.push(`Duration: ${content.duration_minutes} minutes`);
    }
  } else if (contentType === 'quiz' && content?.questions) {
    bodyLines.push(`Quiz with ${content.questions.length} question(s).`);
  } else if (contentType === 'rubric' && content?.criteria) {
    bodyLines.push(`Rubric with ${content.criteria.length} criterion(a).`);
    if (content.total_points) {
      bodyLines.push(`Total points: ${content.total_points}`);
    }
  }

  bodyLines.push('');

  if (options.outputPath) {
    bodyLines.push(`File: ${options.outputPath}`);
    bodyLines.push('');
  }

  // Include serialized content
  bodyLines.push('--- Content (JSON) ---');
  bodyLines.push('');
  try {
    bodyLines.push(JSON.stringify(content, null, 2));
  } catch {
    bodyLines.push('[Content could not be serialized]');
  }

  return {
    subject,
    body: bodyLines.join('\n')
  };
}

/**
 * Build instructions for Claude to send email via himalaya MCP compose_email.
 *
 * Returns a formatted instruction string that Claude should follow to:
 *   1. Preview the email (show recipient, subject, body preview)
 *   2. Ask user to confirm
 *   3. Call himalaya compose_email MCP tool
 *
 * @param {{ to: string, subject: string, body: string }} email - Email parameters
 * @returns {string} Formatted instruction string
 */
export function buildSendInstructions(email) {
  const bodyPreview = email.body.length > 200
    ? email.body.substring(0, 200) + '...'
    : email.body;

  const lines = [];
  lines.push('--- Email Preview ---');
  lines.push(`To: ${email.to}`);
  lines.push(`Subject: ${email.subject}`);
  lines.push(`Body preview: ${bodyPreview}`);
  lines.push('');
  lines.push('To send this email, use the himalaya MCP compose_email tool:');
  lines.push('');
  lines.push('  Tool: compose_email');
  lines.push(`  to: ${email.to}`);
  lines.push(`  subject: ${email.subject}`);
  lines.push('  body: [full email body]');
  lines.push('');
  lines.push('Ask the user to confirm before sending.');

  return lines.join('\n');
}
